force-app/main/default/objects/Escola__c/Escola__c.object-meta.xml
<CustomObject>
    <label>Escola</label>
    <nameField>
        <label>Escola Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escolas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Escola__c/fields/Idioma__c.field-meta.xml
<CustomField>
    <fullName>Idioma__c</fullName>
    <label>Idioma</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Escola__c/fields/Valor_Semana_General__c.field-meta.xml
<CustomField>
    <fullName>Valor_Semana_General__c</fullName>
    <label>Valor por semana general</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Escola__c/fields/Valor_Semana_Part_Time__c.field-meta.xml
<CustomField>
    <fullName>Valor_Semana_Part_Time__c</fullName>
    <label>Valor por semana part time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EscolaREST.cls
@RestResource(urlMapping='/Escola')
global with sharing class EscolaREST {
    @httpGet
    global static List<Escola__c> getEscolas() {
        return [SELECT Id, Name, Idioma__c, Valor_Semana_General__c, Valor_Semana_Part_Time__c FROM Escola__C];
    }

    @httpPost
    global static Escola__c insertEscola(Escola__c escola) {
        //Todo: Aqui podemos fazer qualquer operação.
        insert escola;

        return escola;
    }

    @httpPut
    global static Escola__c upsertEscola(Escola__c escola) {
        //Todo: Aqui podemos fazer qualquer operação.
        upsert escola;

        return escola;
    }

    @httpPatch
    global static Escola__c updateEscola(Escola__c escola) {
        //Todo: Aqui podemos fazer qualquer operação.
        update escola;

        return escola;
    }

    @httpDelete
    global static Boolean deleteEscola() {
        try {
            Id idEscola = (Id)RestContext.request.params.get('Id');
            Escola__c escolaToDelete = new Escola__c(Id = idEscola);

            delete escolaToDelete;
            return true;
        } catch(Exception ex) {
            return false;
        }
    }
}